language: go

go:
  - 1.5

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

install:
  - sudo apt-get update
  - sudo apt-get install libsdl-dev libsdl-image-dev
  - go get -v github.com/veandco/go-sdl2/sdl{,_image}
