language: go

go:
  - 1.5

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update
  - sudo apt-get install libsdl2-dev libsdl2-image-dev
  - go get -v github.com/veandco/go-sdl2/sdl{,_image}
